name = "gf-board"
main = "./worker/index.ts"
compatibility_date = "2025-04-09"
upload_source_maps = true

# Verhindere Config-Umleitung
keep_vars = true

[observability]
enabled = true

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
