name = "gf-board"
main = "./worker/index.ts"
compatibility_date = "2025-04-09"
upload_source_maps = true

# Verhindere Config-Umleitung
keep_vars = true

[observability]
enabled = true

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[kv_namespaces]]
binding = "GF_KIOSK_KV"
id = "placeholder_id"
preview_id = "placeholder_preview_id"
